version: '3.8'
services:
  graphdb:
    image: ontotext/graphdb:10.4.1
    container_name: GuttembergGraph
    ports:
      - "7200:7200"
    volumes:
      - graphdb-data:/opt/graphdb/home
    restart: unless-stopped

volumes:
  graphdb-data:
